---
services:
  astro:
    build: .
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.astro.rule=Host(`astro.dreamnetwork.space`)"
      - "traefik.http.routers.astro.entrypoints=websecure"
      - "traefik.http.routers.astro.tls.certresolver=cloudflare"
      - "traefik.http.services.astro.loadbalancer.server.port=3000"
    networks:
      - frontend

networks:
  frontend:
    external: true
