name: Deploy to Docker

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      env:
        HOST: ${{ secrets.SERVER_HOST }}
        USERNAME: ${{ secrets.SERVER_USERNAME }}
        PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
      run: |
        ssh -o StrictHostKeyChecking=no $USERNAME@$HOST '
          cd $PROJECT_PATH
          git pull origin main
          docker compose down
          docker compose up -d --build
        '
